apiVersion: console.openshift.io/v1
kind: ConsoleNotification
metadata:
  name: banner
spec:
  text: Azure Red Hat OpenShift --PROD--
  location: BannerTop 
  color: '#fff'
  backgroundColor: '#35ab3d'