using './main.bicep'

param location = 'swedencentral'
param deploymentType = 'aro'
param hubResourceGroupName = 'sail-hub-rg'
param hubVnetName = 'sail-hub-vnet'
param hubVnetResourceId = ''
param hubNextHopIpAddress = '10.0.0.4'
param spokeVnetName = 'sail-spoke-vnet'
param spokeAddressPrefix = '10.1.0.0/16'
param masterSubnetName = 'master-subnet'
param masterSubnetPrefix = '10.1.2.0/24'
param workerSubnetName = 'worker-subnet'
param workerSubnetPrefix = '10.1.4.0/23'
param privateEndpointSubnetName = 'pe-subnet'
param privateEndpointSubnetPrefix = '10.1.0.0/24'
param routeTableName = 'aro-route-table'
param clusterResourceGroupName = 'sail-rg'
param managedResourceGroupName = 'sail-managed-rg'
param clusterName = 'aro-sail'
param domain = 'sail'
param aroResourceProviderObjectId = '22508d40-9922-4d07-ae8b-c83ca4d35311'
param pullSecret = readEnvironmentVariable('ARO_PULL_SECRET', '')
param openShiftVersion = ''
