apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-instance
spec:
  project: cluster-services
  source:
    repoURL: https://github.com/erleonard/SAIL-with-ARO.git
    targetRevision: main
    path: gitops/cluster-services/external-secrets/instance
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true