apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cluster-services
  namespace: openshift-gitops
spec:
  description: Project for cluster services components
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'