apiVersion: console.openshift.io/v1
kind: ConsoleNotification
metadata:
  name: banner
spec:
  text: Azure Red Hat OpenShift --DEV--
  location: BannerTop 
  color: '#fff'
  backgroundColor: '#0088ce'
