namespace: openshift-gitops

resources:
  - ../../base

patches:
- patch: |-
    apiVersion: argoproj.io/v1alpha1
    kind: Application
    metadata:
      name: external-secrets-instance
    spec:
      source:
        path: gitops/cluster-services/external-secrets/instance/overlays/non-prod
