namespace: openshift-gitops

resources:
  - ../external-secrets/operator/overlays/non-prod
  # Instance commented out until we have a KV to work with.
  #- ../external-secrets/instance/overlays/non-prod
