apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: azurekv
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: "patched-in-overlay"
      serviceAccountRef:
        name: external-secrets-sa
        namespace: external-secrets-operator