namespace: openshift-gitops

resources:
  - ../../base

patches:
- patch: |-
    apiVersion: argoproj.io/v1alpha1
    kind: Application
    metadata:
      name: cluster-config
      namespace: openshift-gitops
    spec:
      source:
        path: gitops/01-argocd/03-cluster-config/00-prod
- patch: |-
    apiVersion: argoproj.io/v1alpha1
    kind: Application
    metadata:
      name: cluster-services
      namespace: openshift-gitops
    spec:
      source:
        path: gitops/01-argocd/04-cluster-services/prod